"""Sentinel_api migration message

Revision ID: 20ac8383a142
Revises: 
Create Date: 2023-12-23 15:25:03.176026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ac8383a142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elliptic_verifier', schema=None) as batch_op:
        batch_op.alter_column('privateKey',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=1200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elliptic_verifier', schema=None) as batch_op:
        batch_op.alter_column('privateKey',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=800),
               existing_nullable=False)

    # ### end Alembic commands ###
