"""Sentinel_api migration message

Revision ID: 738ac40f1469
Revises: dd727fdd32e7
Create Date: 2024-01-21 16:10:28.454487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738ac40f1469'
down_revision = 'dd727fdd32e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_bucket', schema=None) as batch_op:
        batch_op.drop_constraint('backup_bucket_lifecycle_policy_id_key', type_='unique')

    with op.batch_alter_table('sentinel_iam_access_users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentinel_iam_access_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('backup_bucket', schema=None) as batch_op:
        batch_op.create_unique_constraint('backup_bucket_lifecycle_policy_id_key', ['lifecycle_policy_id'])

    # ### end Alembic commands ###
