"""Sentinel_api migration message

Revision ID: 8e63b14ad463
Revises: 8fb7b10d8447
Create Date: 2023-12-28 16:20:23.343309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e63b14ad463'
down_revision = '8fb7b10d8447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_bucket', schema=None) as batch_op:
        batch_op.drop_constraint('backup_bucket_name_key', type_='unique')

    with op.batch_alter_table('backup_sentinel_kms', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_sentinel_kms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('backup_bucket', schema=None) as batch_op:
        batch_op.create_unique_constraint('backup_bucket_name_key', ['name'])

    # ### end Alembic commands ###
