"""Sentinel_api migration message

Revision ID: 8fb7b10d8447
Revises: 20ac8383a142
Create Date: 2023-12-28 16:11:37.041149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb7b10d8447'
down_revision = '20ac8383a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_bucket',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('bucket_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('lifecycle_policy_id', sa.String(length=200), nullable=True),
    sa.Column('sentinel_kms_id', sa.String(length=200), nullable=True),
    sa.Column('availability', sa.String(length=200), nullable=True),
    sa.Column('backup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lifecycle_policy_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backup_file',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('backup_bucket_id', sa.String(length=200), nullable=True),
    sa.Column('file_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('bucket_id', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('temp_deleted', sa.String(length=200), nullable=True),
    sa.Column('restore_time_limit', sa.DateTime(), nullable=True),
    sa.Column('time_to_delete', sa.DateTime(), nullable=True),
    sa.Column('permanently_deleted', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_sentinel_kms',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('backup_bucket_id', sa.String(length=200), nullable=True),
    sa.Column('kms_id', sa.String(length=200), nullable=True),
    sa.Column('last_date_of_rotation', sa.DateTime(), nullable=True),
    sa.Column('encryption_key', sa.String(length=300), nullable=False),
    sa.Column('bucket_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bucket_access_backup',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('backup_bucket_id', sa.String(length=200), nullable=True),
    sa.Column('acl_id', sa.String(length=200), nullable=True),
    sa.Column('bucket_id', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_policy_backup',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('backup_bucket_id', sa.String(length=200), nullable=True),
    sa.Column('lifecycle_id', sa.String(length=200), nullable=True),
    sa.Column('days_to_archive', sa.Integer(), nullable=True),
    sa.Column('days_to_permanent_deletion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bucket_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bucket_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('lifecycle_policy_backup')
    op.drop_table('bucket_access_backup')
    op.drop_table('backup_sentinel_kms')
    op.drop_table('backup_file')
    op.drop_table('backup_bucket')
    # ### end Alembic commands ###
