"""Sentinel_api migration message

Revision ID: 912a356018ea
Revises: 8e63b14ad463
Create Date: 2023-12-28 20:59:37.551208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912a356018ea'
down_revision = '8e63b14ad463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_block_list',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('block_ip', sa.String(length=200), nullable=False),
    sa.Column('time_of_add', sa.DateTime(), nullable=True),
    sa.Column('time_of_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firewall_block_list')
    # ### end Alembic commands ###
