"""Sentinel_api migration message

Revision ID: ba191901989f
Revises: 912a356018ea
Create Date: 2024-01-02 16:40:29.916782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba191901989f'
down_revision = '912a356018ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_communication_securer',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('nonce', sa.String(length=300), nullable=False),
    sa.Column('aad', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_communication_securer')
    # ### end Alembic commands ###
